### ISSUE TITLE
add faucet button to sidebar

### ISSUE THREAD

**Issue by DarkNebula0** [gamedaoco/gamedao-beta#109]

**Comment by 5-mark** [comment]
@DarkNebula0 I can see a link on the dashboard page but no button in the sidebar. 
![image](https://user-images.githubusercontent.com/91988132/142236440-888031b9-372b-4bb9-9f69-514f4002aecf.png)
But when clicking the link I sign a transaction but nothing else happened with my Zero, Game & Play balance. 
what should be the expected outcome?
From my point of view I should receive 10 Game, 10 Zero & 10 Play, no?

**Comment by DarkNebula0** [comment]
![image](https://user-images.githubusercontent.com/91988910/142237248-54cbbf71-b8d2-4dd1-9a84-2d046bf7d252.png)

The button in the sidebar should take you to the discord channel.

The button on the dashboard is only a transaction demo and can be removed.

**Comment by 5-mark** [comment]
Ok cool, @DarkNebula0 Thanks. I can see the faucet button now 👍🏼
