### ISSUE TITLE
Create proposal doesnt work

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-beta#142]
**Describe the bug**
When creating a proposal the console reponds with an error on form submit. 

**To Reproduce**
1. Go to "Votings"
2. Click "+ New Proposal"
3. Select first organization (only address visble, not Organization name
4. write sth. in the title and description (not the standard text)
5. select Voting Type "Single Choice"
6. duration = 1d
7. collateral type = GAME
8. collateral amount = 1 
9. amount to transfer = 1
10. click submit button and receive error in console:
![image](https://user-images.githubusercontent.com/91988132/143691128-0674c1e8-5db6-4545-bb39-8133b03bc46b.png)

`fetch.browser.js:106 POST https://ipfs.gamedao.co/api/v0/add?stream-channels=true&progress=false 500
HTTPError: committing batch to datastore at /blocks: mkdir /data/ipfs/blocks/JT: no space left on device
    at core.js:84
    at l (runtime.js:63)
    at Generator._invoke (runtime.js:294)
    at Generator.next (runtime.js:119)
    at n (asyncToGenerator.js:3)
    at u (asyncToGenerator.js:25)`

**Expected behavior**
- no error should appear, transaction window from wallet should appear
- after signing the transaction the Proposal is visible
- organizations drop down should contain organization name instead of hash

**Additional context**
if i leave everything filled with standard data the sign transaction window appears, after singing successfully the platform responds with a "proposal creation successfully" message but the new proposal is still not there (also not after reload).
No event appears in polkadot.js wallet under Network/Chain info/recent events.

**Comment by 2075** [comment]
please do not post screenshots of error messages, but copy the text. this will enable finding errors like this in the future.

**Comment by 2075** [comment]
reading the error message also tells us, that @DarkNebula0 needs to increase the volume size on ipfs to be able to upload files again: the disk is full.

**Comment by 2075** [comment]
seems to work now, but page does not redirect to either overview or detail page of the voting after successful creation.
