### ISSUE TITLE
Organizations Detail Page

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-beta#152]
## User Story
As user I want to see more details of an Organization so I can inform myself about the Organization.

## Acceptance Criteria

1. Create Organizations detail page
2. Click on main image and title on Organizations List Page leads to Organizations Detail Page
3. The organizations detail page is separated into single pages which are managed via top navigation
4. On all pages the left column with the DAO's meta information is shown
4.1 Organization logo, organization name and member amount is shown
4.2 "join" CTA if user is no member and DAO is public or not loggedin
4.3 "Apply" CTA if organization is private
4.4 "Leave" if user is member
5. Overview page
5.1 The organization description is shown within the first box
5.2 A preview of proposal (votings) is shown on second place
5.3 If no votings are available it shows a placholder text and CTA to add proposal
5.4 A preview of campaigns is shown on the third place
5.5 if no campaigns are available it shows a placeholder text and CTA to create campaign

6. Campaigns
6.1 The campaigns subpage show a list of 2 campaigns
6.2 The list is sortable
6.3 If more than 2 campaigns are shown, a pagination is shown

7. Votings
7.1 Shows a list of proposals
7.2 The Title, corresponding DAO and expiry date is shown in the first column
7.3 The status is shown on the second column
7.4 A call to action is shown in the third column
7.5 Depending on the status the call to action is either "Vote" or "See details" 
7.6 The list can be sorted, default sorting is based on expiry date: newest to oldest
Note: The voting list uses the same design as the voting overview page, makes sense to reuse components

8. Members
8.1 Shows a list of members
8.2 The first column "Member" shows the profile picture, identity and address
8.3 If no identity is set, it only shows the address
8.4 The second column shows the shares
8.5 The third column shows the join date
8.6 The list can be sorted, default sorting is based on share amound (highest to lowest)

9. Settings (?)
_to be defined in case it's relevant_

## Additional Information
Design: https://www.figma.com/file/LmFOAGwKieWxmLtFVulChX/GameDAO-Frontend-Design?node-id=1098%3A9171

- MVP works also without vanity URL 

## How to test

1. Go to Organizations List Page
2. Clickt the image or the title
3. land on the organizations detail page (see url with hash )

**Comment by mikeplanzer** [comment]
Hi @DarkNebula0, the ticket is now refined and designs are updated. Please let me know if you need a walkthrough or have any questions.
