### ISSUE TITLE
fix issues on Organizations List Page

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-beta#153]
**Describe the bug**
Several inconsistencies are visible today on the Organizations List Page:

**Issues to fix**
1. "open" and "locked" are confused. For open organizations "locked" is displayed and vice versa. -> should be the other way around
2. rename "open" to "public" and "locked" to "private"
3. remove address hash within close button when creating new Organization
4. correct usage of singular and plural (members are currently always with "s", also if only 1 member -> should be "member" when only 1 member)

**Comment by 5-mark** [comment]
AC4 seems to be not done:
![image](https://user-images.githubusercontent.com/91988132/145485013-ef50ba1d-0998-4290-858c-f79872a5ad54.png)

**Comment by 5-mark** [comment]
@DarkNebula0 & @soundyogi since it is required to have at least 2 different members in a DAO AC4 doesnt need to be fixed.

**Comment by 2075** [comment]
we still need pluralisation for e.g. contributors.
