### ISSUE TITLE
everybody can leave the 1 member organisation

### ISSUE THREAD

**Issue by 2075** [gamedaoco/gamedao-beta#158]
**Describe the bug**
users are offered the leave button instead of apply

**To Reproduce**
- browse organisations
- lab75 shows 1 member and leave button
- change account, still shows leave button
- change computer with another account, still shows leave button

**Expected behavior**
- users who are member should be able to leave
- users who are not member should be able to apply or join

**Screenshots**
![image](https://user-images.githubusercontent.com/1140449/143872230-9ceae6de-5505-498a-bf64-9f15ab2ece72.png)

**Desktop (please complete the following information):**
n.a.
**Smartphone (please complete the following information):**
 n.a.

**Additional context**

**Comment by 5-mark** [comment]
currently no defaults are set for users who did not interact with this organisation. (gameDaoControl:bodyMemberState = 1)
maybe check before if isMember?

**Comment by 2075** [comment]
1. to check membership in a reliable fashion you can use memberships(AccountId) - it should deliver you a list of hashes where account is member of.

2. also you can manually check with an extrinsic check_membership(Hash) which checks if the caller is a member of Hash.

memberstate was meant to reflect the member state in process of joining or being kicked out, to have different states eg when there is a voting to let someone join.
