### ISSUE TITLE
Proposal form: Organisation List contains address hashes

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-beta#170]
**Describe the bug**
When clicking into the organisations select box of the create proposal form only address hashes appear of all available organisations, instead of only organisation names.

**To Reproduce**
1. Go to [https://beta.gamedao.co/app/governance](https://beta.gamedao.co/app/governance )
2. Click on "New Proposal"
3. Click on Organisations/Campaigs select box 
4. See address hashes from all organisations 

**Expected behavior**
the  Organisations/Campaigns select box only shows organisation & campaign names.
 
**Screenshots**
![image](https://user-images.githubusercontent.com/91988132/144292182-aa159cf9-7581-49af-9e9a-df61104d5532.png)

**Comment by PAkhidue** [comment]
QA can be done here: https://gamedao-beta-28lf5kpfm-75.vercel.app/
