### ISSUE TITLE
Vote on simple majority proposal

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-beta#171]
## User Story
As user I want to be able to vote on a simple majority proposal so I can take part in the decision taking process.

## Acceptance Criteria

1. Being member of an Organisation with an active proposal the member shall be able to vote with Yes or No on this proposal
2. Being not a member of an Organisation the user shall not be able to vote on the proposal
2.1 Instead the snack bar should respond with "Join the organisation to access voting rights" 
3. after successful voting (snackbar shows up) the view updates with the result visible in numbers and the colored bar 
4. the voter address and the vote (Yes or No) will be visible below the voting details
5. the design of the voting detail page is as visualized in figma (start & end date +time, buttons, colors (see below)

## Additional Information

- https://www.figma.com/file/LmFOAGwKieWxmLtFVulChX/GameDAO-Frontend-Design?node-id=530%3A8745
Figma does not contain the DAO and the DAO name but we should keep it (and rename DAO --> Organisation)

## How to test being member

1. go to active proposal
2. make sure you are online with a wallet which is member of the DAO proposing the voting
3. vote with the nice yes or no button
4. sign transaction
5. see snackbar success message
6. see updated result on the proposal detail page

## How to test not being member
1. go to active proposal
2. make sure you are online with a wallet which is member of the DAO proposing the voting
3. vote with the nice yes or no button
4. receive snack bar message as in AC 2.1

**Comment by PAkhidue** [comment]
@5-mark should we really just rename DAO to Organization? What happens if you select a campaign instead of a DAO?
Currently this case wouldn't be handled.

I guess we should also show the campaign if selected while creating the proposal.

**Comment by 5-mark** [comment]
@PAkhidue: lets see first if campaigns even show up in the select box. But for now we decided to always speak about "Organisations" instead of "DAOs".
