### ISSUE TITLE
Leave Organisation

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-beta#173]
**Describe the bug**
As a member of an Organisation clicking on the leave button the signed transaction does not lead to leaving the organization.

**To Reproduce**
1. Go to Organization List Page
2. Make sure you are member of an organization
3. Click the Organization "Leave" Button
4. Sign the transaction
5. view event log in polkadot.js wallet 
6. see that gameDaoControl.RemoveMember and gameDaoControl.AddMember (see screenshot) is called and  see on the organization list page that you are still (or again) member  

**Expected behavior**
When the "Leave" transaction was successful the member is not part of the Organization any more and receives back his reserved amount of token back to his wallet address, when the Organization "Fee Model" is "reserve".

**Screenshots**
![image](https://user-images.githubusercontent.com/91988132/144312998-56dd6898-0791-4a50-9cc5-6ed1aa664d09.png)

**Additional context**
seems like something in the corresponding pallet is misconfigured

**Comment by 2075** [comment]
works on chain

**Comment by 2075** [comment]
![Screenshot 2021-12-10 at 21 04 02](https://user-images.githubusercontent.com/1140449/145634735-06845833-2a93-48bf-b65a-3e01ba447406.png)

**Comment by 2075** [comment]
@5-mark @DarkNebula0
