### ISSUE TITLE
Unable to use fractional Membership fee

### ISSUE THREAD

**Issue by cryply** [gamedaoco/gamedao-beta#186]
**Describe the bug**
While creating DAO I was unable to use 0.1 as membership fee

**To Reproduce**
I was unable to create DAO due to fact I am using fractional numbers
How to repeat:

1. Go to https://beta.gamedao.co/app/organisations
2. Leave everything unchanged
3. Enter 0.1 as Membership fee
4. Click Create Organization

Development Console shows Error:
Uncaught (in promise) Error: createType(Call):: Call: failed decoding gameDaoControl.create:: Struct: failed on args: {"creator":"AccountId","controller":"AccountId","treasury":"AccountId","name":"Bytes","cid":"Bytes","body":"u8","access":"u8","fee_model":"u8","fee":"Balance","gov_asset":"u8","pay_asset":"u8","member_limit":"u64"}:: Struct: failed on fee: Balance:: Balance: Negative number passed to unsigned type

**Expected behavior**
1. If fractional fee not supported I expect clear JS warning about it.
2. 0.1 is clearly not negative number so underlying level incorrect.
3. UI should prevent from entering and submitting invalid values.

**Screenshots**
![image](https://user-images.githubusercontent.com/36797566/144749025-9324116b-e03f-4648-9dc9-1a96e76d6e24.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Browser Firefox 94 64bit

**Additional context**
I got enough ZERO on my wallet 39

**Comment by 2075** [comment]
values need to be properly converted, e.g. with the polkadot utils

**Comment by 2075** [comment]
seems to work as expected now @5-mark @DarkNebula0
