### ISSUE TITLE
Form layout for image upload

### ISSUE THREAD

**Issue by mikeplanzer** [gamedaoco/gamedao-beta#191]
## User Story
As ux manager I want to update the form layout for the image upload to achieve better usability for the user.

## Acceptance Criteria

1. Don't show the placeholder image from the beginning (when no images is uploaded yet)
2. Only show the image as a preview as soon as an asset is uploaded
3. Add placeholder copy "Drop an image here, or select a file."
4. An an extra line below point 3m add placeholder for image specs Like "It must be a JPG or PNG, 1920 x 800px and no larger than 200 MB."
5. Light Mode: Add border, same color as for input fields can be used
6. Change border from solid to dashed for the file upload inputs
7. When assets is uploaded, it can be removed via clicking the X on the right corner

## Additional Information
⭐ **Design**: 
https://www.figma.com/file/LmFOAGwKieWxmLtFVulChX/GameDAO-Frontend-Design?node-id=1025%3A7165 

## How to test

1. Go to GameDAO beta
2. Navigate to campaigns and click on "create new campaign"
4. See if changes on the frontend are done according to ACs

**Comment by 5-mark** [comment]
1. Don't show the placeholder image from the beginning (when no images is uploaded yet) ✅ 
2. Only show the image as a preview as soon as an asset is uploaded ✅ 
3. Add placeholder copy "Drop an image here, or select a file." ❌ 
4. An an extra line below point 3m add placeholder for image specs Like "It must be a JPG or PNG, 1920 x 800px and no larger than 200 MB." ❌ 
5. Light Mode: Add border, same color as for input fields can be used ❓ 
6. Change border from solid to dashed for the file upload inputs ❓ @mikeplanzer: _cannot see in figma_ 
7. When assets is uploaded, it can be removed via clicking the X on the right corner ❌

**Comment by soundyogi** [comment]
Don't show the placeholder image from the beginning (when no images is uploaded yet)✅
Only show the image as a preview as soon as an asset is uploaded✅
Add placeholder copy "Drop an image here, or select a file."✅
An an extra line below point 3m add placeholder for image specs Like "It must be a JPG or PNG, 1920 x 800px and no larger than 200 MB." ✅
Light Mode: Add border, same color as for input fields can be used✅
Change border from solid to dashed for the file upload inputs✅
When assets is uploaded, it can be removed via clicking the X on the right corner✅

**Comment by soundyogi** [comment]
https://github.com/gamedaoco/gamedao-beta/pull/237

**Comment by 5-mark** [comment]
@soundyogi AC4 text is not where it should be:
![image](https://user-images.githubusercontent.com/91988132/146784184-8951bc54-8e71-4c27-ab62-6ca17b480360.png)

it should be here:
![image](https://user-images.githubusercontent.com/91988132/146784304-fc75b042-43b7-4ac7-af86-b64ba5a1f27a.png)

**Comment by soundyogi** [comment]
oops. changed.

**Comment by soundyogi** [comment]
![image](https://user-images.githubusercontent.com/3201046/146790986-ab27327b-c169-4274-9581-e55af822da18.png)

**Comment by soundyogi** [comment]
![image](https://user-images.githubusercontent.com/3201046/146791158-8e765625-e896-4cbf-a166-b59f96ac67d0.png)

**Comment by 5-mark** [comment]
looks better now, what happens with the PR?

**Comment by soundyogi** [comment]
this ticket will be closed when you merge it
