### ISSUE TITLE
Create DAO throws error

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-beta#202]
**Describe the bug**
Creating a dao results in an error

**To Reproduce**
1. Go to Organisations
2. Create new DAO
3. loader loads and does not respond / no error in console
4. reload page 
5. try again 
6. receive this error

```
Transaction failing with Error: 1014: Priority is too low: (39322346625964751 vs 39322211500913764): The transaction has too low priority to replace another transaction already in the pool.
    at e.value (4.47b6bee1.chunk.js:2)
    at e.value (4.47b6bee1.chunk.js:2)
    at e.value (4.47b6bee1.chunk.js:2)
    at WebSocket.value (4.47b6bee1.chunk.js:2)
```

**Expected behavior**
DAO gets created

**Comment by 2075** [comment]
add input validation to fields and balances:
1. every account needs to be different
2. every account needs to have enough balance to cover member fee
3. works as expected

![Screenshot 2021-12-10 at 22 41 58](https://user-images.githubusercontent.com/1140449/145645257-5b74dba4-a187-4d03-864d-56b6045b6284.png)

![Screenshot 2021-12-10 at 22 43 45](https://user-images.githubusercontent.com/1140449/145645267-3cc0a9b8-a2aa-4887-9533-36a4fb321a4a.png)

**Comment by 5-mark** [comment]
Still does not work for me:
![image](https://user-images.githubusercontent.com/91988132/145647413-ba73f13c-55b2-4edc-a245-e4962be8cef1.png)

@2075 what do you mean with every account needs to be different? different in what?
I have enough balance to cover membership fee. Nothing is reserved from that account, just obtained some fresh zero.

**Comment by 2075** [comment]
@5-mark just read the instructions.



    every account needs to be different
    every account needs to have enough balance to cover member fee
