### ISSUE TITLE
wallet does not stick to selected account on page reload

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-beta#208]
**Describe the bug**
when choosing another wallet and clicking to another page or button then the initial selected wallet is re-selected.

**To Reproduce**
1. be loggedin and go to campaign page
2. select another wallet 
3. click new campaign
4. See wallet switches to initial wallet. 

**Expected behavior**
the selected wallet remains selected until I select another wallet.

**Comment by 2075** [comment]
the original ticket was about the following scenarios:

A
1. connect wallet
2. select an account ( not the first )
3. disconnect
4. reconnect -> first account is selected

B
1. connect wallet
2. select an account
3. disconnect
4. reload -> reconnects even user decided to disconnect

@5-mark 
@DarkNebula0 -> do you need a new ticket for these?

**Comment by 5-mark** [comment]
@2075 & @DarkNebula0  created #242 for the remaining error
