### ISSUE TITLE
add: missing form validations

### ISSUE THREAD

**Issue by soundyogi** [gamedaoco/gamedao-beta#211]
## User Story
As user I want to get proper feedback if my form input is not valid, so I can correct it to be able to successfully submit the form.

## Acceptance Criteria

1. create organization form: form field: validator, message
1.1 organization name: max-length 50 characters, "Please enter a maximum of 50 characters."
1.2 email: email validator, "Please enter a valid e-mail address."
1.3 Website: url validator, "Please enter a valid URL."
1.4 Controller account: polkadot/kusama address validator where the actual network address can be derived from, "Please enter a valid network address."
1.5 Treasury account,
1.5.1 same validator as for Controller Account + same message 
1.5.2 validate if the same address was used for the Controller Account (inline +onSubmit), "Treasury Account may not be the same account as Controller Account.
1.6 member limit: integer validator, "Please enter the maximum number of members."
1.7 membership fee: decimals validator, "Please enter the membership fee." 
1.8 instead of the text "Note: In case you want to create a DAO, the controller must be the organization." please use the text: "Note: The treasury account may not be the same as the controller account."
2. create campaign form
2.1 Campaign name: max-length 50 characters, "Please enter a maximum of 50 characters."
2.2 Public Representative: only letters validator, "Please enter only letters."
2.3 email: email validator, "Please enter a valid e-mail address."
2.4 Deposit (GAME): token amount validator (eg. up to 18 digits), "Please enter deposit amount."
2.5 Funding Target (PLAY): token amount validator (eg. up to 18 digits), "Please enter funding target."
3. Create Proposal form
3.1 Proposal title: max-length 50 characters, "Please enter a maximum of 50 characters."
3.2 Collateral amount: token amount validator (eg. up to 18 digits), "Please enter collateral amount."

## Additional Information

- use standard MUI styles to display error messages

## How to test

1. go through all 3 forms and enter invalid data to see error messages
2. also manipulate input so that errors get catched on form submit

**Comment by 5-mark** [comment]
@soundyogi: not sure if I got the right version. I tested on https://gamedao-beta-7h7dfenh2-75.vercel.app/app/
But many things no worky yet.

- Entering values in the Organization name field triggers error message in email and short description field -> each field should be validated on its own. Also no max-lengths implemented. 
![image](https://user-images.githubusercontent.com/91988132/146641231-a8e2e5d4-ac0d-4053-8971-67c597cb7be4.png)

- please consider AC1.3 --> not an url validator
- AC1.4 & AC1.5.1 no polkadot address validator implemented
- AC1.6 & AC1.7 possible to enter chars in member limit and member fee fields, shou
- please consider AC1.8

- AC2.1 no maxlength reflected and selecting a DAO triggers error messages in other fields:
![image](https://user-images.githubusercontent.com/91988132/146641211-52da995c-0743-4e28-9cb2-4dec5cba5315.png)
- AC2.3 not reflected
- AC2.4 not reflected (but 2.5 is)

-AC3.1 not reflected 
AC3.2 does not apply (will strike strough)

**Comment by 2075** [comment]
for data efficiency we should use 48bytes max length

**Comment by soundyogi** [comment]
create organization form: form field: validator, message
✅1.1 organization name: max-length 50 characters, "Please enter a maximum of 50 characters."
  _for data efficiency we should use 48bytes max length - added_
✅1.2 email: email validator, "Please enter a valid e-mail address."
✅1.3 Website: url validator, "Please enter a valid URL."
✅1.4 Controller account: polkadot/kusama address validator where the actual network address can be derived from, "Please enter a valid network address."
✅1.5 Treasury account,
✅1.5.1 same validator as for Controller Account + same message
✅1.5.2 validate if the same address was used for the Controller Account (inline +onSubmit), "Treasury Account may not be the same account as Controller Account.
###    **needs better account address validator only checks for length of 47 now!**
✅1.6 member limit: integer validator, "Please enter the maximum number of members."
✅1.7 membership fee: decimals validator, "Please enter the membership fee."
✅1.8 instead of the text "Note: In case you want to create a DAO, the controller must be the organization." please use the text: "Note: The treasury account may not be the same as the controller account."
create campaign form
✅2.1 Campaign name: max-length 50 characters, "Please enter a maximum of 50 characters."
 _for data efficiency we should use 48bytes max length - added_
✅2.2 Public Representative: only letters validator, "Please enter only letters."
✅2.3 email: email validator, "Please enter a valid e-mail address."
✅2.4 Deposit (GAME): token amount validator (eg. up to 18 digits), "Please enter deposit amount."
✅2.5 Funding Target (PLAY): token amount validator (eg. up to 18 digits), "Please enter funding target."
