### ISSUE TITLE
Release campaign funds proposal

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-beta#224]
## User Story
As organisation controller I want to create a proposal on releasing the funds of a funded campaign to the campaign organisation treasury account so I can make use of the funds. 

## Acceptance Criteria

1. When creating a proposal on a campaign which is funded and the end date is reached:
1.1 the only proposal type is "Withdrawal" and preselected
1.2. The Voting Type is "Simple Majority"
2. When the propsal is created, expired and voted for with YES, 
2.2 the in the organisation treasury reserved funds* change their status from reserved to available 
3. When the propsal is created, expired and voted for with NO, 
3.1 The funds are transferred back to every backer in the size of their contribution

## Additional Information

*the funds are transferred automatically by the network protocol to the Organisation Treasury account minus GameDAO fees which are transferred to the GameDAO Treasury account as soon as the fundraising campaign completes (funded & expried).
- dependent on #243 , #244

## How to test

1. Create DAO, create campaign and let users contribute until the campaign is funded and expired
2. see funds are transferred to GameDAO and Organisation treasury accounts (reserved)
3. create a proposal as the dao controller to release the campaign funds in the dao treasury account 
4. get simple majority of the votes for yes
5. 6. repeat 1 & 2 
7. get simple majority for NO
8. see funds are transferred back to each contributor (excluding fees)

**Comment by 2075** [comment]
just to add some sidenotes:

1. when the fundraising campaing completes, fundraising (FLOW) pallet collects all the funds, moves them to the creator treasury (account which is currently set manually — should be automatically selected and not changeable to organisatiosn treasury account) and blocked (reserved). so the recipient is already in custody of the funds but cannot access. also the gamedao treasury receives their commission.

2. withdrawal voting can be created by org controller ("president", "prime" ?) and results in a withdrawal voting on chain.

3. then vs described above 3.1 fees aere immediately taken on campaign finalisation, not on each withdrawal

tbc

**Comment by 5-mark** [comment]
Thanks @2075 for the input,
I changed the ACs and the test scenario accordingly. 
regarding 1.)
does this work already? If yes we should be able to see that on this campaign and its corresponding org treasury account (funds reserved) 
https://beta.gamedao.co/app/campaigns/0xb393d2e78c8e25df91ff519833509e44c03d7ab63a81ffc660b471f6af17b5f5

2.) user story contains the org controller. (only he shall be able to create withdrawal proposals - at least for beta) )
3.) changed the ACs.

**Comment by 2075** [comment]
![image](https://user-images.githubusercontent.com/1140449/146463210-9030f4af-3eb8-4722-ac73-86bb06f9e532.png)
- dao creation
- campaign creation
- campaign contribution
- campaign succeeded
- transfer and lock in creator account
- withdrawal proposal
- settlement and unreserve for creator account

**Comment by 2075** [comment]
https://github.com/playzero/subzero/commit/9e8dcb1b1f80fcd023b2c255e24150aa275dc3a1

**Comment by 2075** [comment]
anybody wanna test? @5-mark @DarkNebula0 @soundyogi @PAkhidue

**Comment by 5-mark** [comment]
test worked like a charm @2075 @soundyogi @DarkNebula0 @PAkhidue @jaaydenh:

I used polkadot wallet and 
* created a campaign which runs out in a couple of minutes (used main account)
* funded the campaign through the frontend with 2 different accounts
* created a withdrawal proposal through polkadot wallet with DAO controller account
* couldnt see this proposal on the frontend and voted therefore through polkadot wallet with a user which funded the campaign
* vote result was yes and after expiry my DAO controller account got rich (_possible the funds should have been transferred to the DAO treasury account?_) 
* the funding accounts have no reservations left and got poor but look forward for some new game :-)

There are no blockers for this tickets left. Thanks @2075 💯

**Comment by 2075** [comment]
what's the next step? @5-mark @PAkhidue @DarkNebula0 @soundyogi

**Comment by 5-mark** [comment]
bugs and test captured in gamedaoco/gamedao-refinement#13
