### ISSUE TITLE
Create DAO : Convert all addresses to current network format

### ISSUE THREAD

**Issue by cryply** [gamedaoco/gamedao-beta#236]
**Describe the bug**
While Creating DAO autofilled with KUSAMA address of current polka account it not obvious that we must provide Treasury address also in that format.

**To Reproduce**
1. Go to https://beta.gamedao.co/app/organisations
2. Click on New DAO
3. Scroll down to Treasury address 
4. Try to figure out what to enter there.

**Expected behavior**
We must provide info on which chain we operate. We must validate address and give a tip if address in wrong format.

**Screenshots**
![image](https://user-images.githubusercontent.com/36797566/146688094-62c36477-612e-420b-bfa1-578010a9b24c.png)

**Comment by 2075** [comment]
it is incorrect, actually we accept all network formats, the validation is just broken @soundyogi

**Comment by cryply** [comment]
So do u accept mixed networks addresses?

**Comment by soundyogi** [comment]
im on it

https://github.com/polkadot-js/common/blob/master/packages/util-crypto/src/address/check.ts
