### ISSUE TITLE
Governance: save proposal voter list with the proposal type

### ISSUE THREAD

**Issue by PAkhidue** [gamedaoco/gamedao-beta#241]
## User Story
As a user I want to see other user votes on the detailed proposal info so we have transparency about the participation.

## Acceptance Criteria

1. Add a list grouped by proposal id with all voters (address) and the proposal type (what they elected)

## How to test

1. Query the proposal voter list with the given proposal id
2. Get a list of all voters with the proposal type / what they voted for

**Comment by 2075** [comment]
@inan @PAkhidue the proposal type is not what they voted but the type of the proposal all together, like general proposal, withdrawal, membership.

i assume you are looking for the actual vote of each user for a proposal, e.g. "yes" or "no", "accept" or "reject", true or false.

**Comment by 2075** [comment]
?

**Comment by 5-mark** [comment]
yes

**Comment by PAkhidue** [comment]
Correct, sorry I used the wrong word.

> @Inan @PAkhidue the proposal type is not what they voted but the type of the proposal all together, like general proposal, withdrawal, membership.
> 
> i assume you are looking for the actual vote of each user for a proposal, e.g. "yes" or "no", "accept" or "reject", true or false.

**Comment by 2075** [comment]
okay, just wanted to make sure. should work on chain already :)

**Comment by 5-mark** [comment]
@PAkhidue works already like 🏅  with `gameDaoGovernance.proposalVotesByVoters`

![image](https://user-images.githubusercontent.com/91988132/147485274-122b886e-f143-4b78-9fb0-4097d14dec8e.png)

please proceed with #194 👍🏼
