### ISSUE TITLE
List campaigns of an organization

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-beta#243]
As frontend developer I want to access a list of campaigns which belong to a certain organisation so I can display them in a select box.

## Acceptance Criteria

1. API which exposes all campaigns of an organisation is provided

## Additional Information

- There is already a view which displays campaigns that belong to an organisation on each organisation detail page like here: 
https://beta.gamedao.co/app/organisations/0xd0774eed8c2622b2b2f496e184c4886b623349a2ede20ad2949d298acb0420aa

List shall be used in proposal form to vote on campaigns.

**Comment by 2075** [comment]
should be provided in version 1.33.0: https://github.com/playzero/subzero/commit/6126fdc72cb208ef8f944051ec46aa4ab50ba0eb

**Comment by 2075** [comment]
1. create organisation
2. create campaign
3. query chain state gameDaoCrowdfunding.campaignsByBody( Body Hash) resolves Vec< Campaign Hash > 

requires new campaigns, as the old ones are not migrated.

**Comment by 5-mark** [comment]
@PAkhidue you can now start implementing #244, can you please check before if you can retrieve with the provided state query campaigns and then close this ticket if successful?

**Comment by 5-mark** [comment]
works 👍🏼 
![image](https://user-images.githubusercontent.com/91988132/147483656-9871346a-3b89-4df7-abfd-96c5aab161e5.png)
