### ISSUE TITLE
Proposal Title gets empty when typing sth into markdown editor

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-beta#247]
**Describe the bug**
When entering a proposal title in the create proposal form and tabbing into the markdown editor and start typing the proposal title gets empty. 

**To Reproduce**
1. Go to create proposal page
2. Enter sth into proposal title
3. Enter sth into markdown editor
4. See proposal title gets empty

**Expected behavior**
form values stay in the input fields as long as I dont leave the page

**Additional context**
Maybe sth went wrong with clearing the form fields and not storing the values forever.

**Comment by 2075** [comment]
input in markdown triggers form reset, looking into it.
