### ISSUE TITLE
Campaign creation and voting doesnt work

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-beta#248]
**Describe the bug**
When creating a campaign on beta gamedao I receive a success message but no event is triggered and no campaign is created. 
Same applies on voting on a proposal

**To Reproduce**
1. Go to Campaigns
2. Create a campaign
3. receive success message and look into polkadot.js > network explorer > recent events
4. See that no event was triggered

1. Go to a proposal which is votable
2. vote on it
3. see success message and look into polkadot.js > network explorer > recent events
4. 4. See that no event was triggered

**Expected behavior**
Getting a success message should trigger a result. In fact a success message should only be shown on success. 

**Additional Information**
- no error messages are shown in the console

**Comment by 2075** [comment]
at least on chain campaign creation works as expected.
is there a console log?

![Screenshot 2021-12-23 at 12 06 30](https://user-images.githubusercontent.com/1140449/147244721-574d26dd-13a4-4d1a-a44e-5d4d10c9d0f2.png)
