### ISSUE TITLE
Unable to create proposal

### ISSUE THREAD

**Issue by cryply** [gamedaoco/gamedao-beta#250]
**Describe the bug**
Creation of proposal failed

**To Reproduce**
1. Go to DAO u own. 
2. Click on New Proposal
3. Select your organization
4. Click publish proposal
5. see error : Proposal Creation failed.

**Expected behavior**
New proposal created

**Screenshots**
![image](https://user-images.githubusercontent.com/36797566/147587732-4e1c795c-2fe2-4776-b9eb-f118f842c1b4.png)

**Additional context**
 I have only ZERO tokens while there no ZERO in collateral types.
![image](https://user-images.githubusercontent.com/36797566/147587820-36008946-801d-46ca-9757-c06b0348a68d.png)

**Comment by 2075** [comment]
@PAkhidue @DarkNebula0 @5-mark

**Comment by 2075** [comment]
@cryply
- collateral is not neccessary yet
- PLAY and GAME can be obtained through the faucet!
- ZERO not needed, as it is a network token, gamedao runs network agnostic.
