### ISSUE TITLE
CORS error during creation of Campaign

### ISSUE THREAD

**Issue by cryply** [gamedaoco/gamedao-beta#251]
**Describe the bug**
Something undefined requested during creation of campaign

**To Reproduce**
1. Go to DAO you own
2. Click on create Campaign
3. Fill up all necessary fields including adding images for logo and header 
4. Click Create Campaign
5. in Dev Console see an error

**Expected behavior**
Clean log without errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/36797566/147588507-d282b57e-66b3-4014-969d-e54b178d874b.png)

**Comment by 2075** [comment]
@DarkNebula0 ipfs setup

**Comment by 5-mark** [comment]
fixed
