### ISSUE TITLE
Unable to enter text of proposals Title in utf-8

### ISSUE THREAD

**Issue by cryply** [gamedaoco/gamedao-beta#260]
**Describe the bug**
its impossible to enter Proposal Title in Chinese

**To Reproduce**
1. Go to your own DAO
2. Click on New Proposal
3. Scroll down to Proposal Title
4. try to enter : 好久不见
5. Proposal Title frame red:

**Expected behavior**
any utf-8 characters should be allowed as Title

**Screenshots**
![image](https://user-images.githubusercontent.com/36797566/148219695-ed0bb01c-8850-444a-b81f-e87b066b224c.png)

**Comment by 2075** [comment]
input fields should allow international content

**Comment by DarkNebula0** [comment]
@cryply I think the title must have more than 5 characters

![image](https://user-images.githubusercontent.com/91988910/148425312-b1cfa26e-06e8-430e-8959-b18b67097c1e.png)

**Comment by cryply** [comment]
FE should clearly inform about this

**Comment by cryply** [comment]
In Chinese and Japanese 1 character can be one word.

**Comment by 5-mark** [comment]
✅
