### ISSUE TITLE
Unable to contribute to own campaign error visible only in development console log.

### ISSUE THREAD

**Issue by cryply** [gamedaoco/gamedao-beta#261]
**Describe the bug**
I was testing my campaign and my attempt to contribute failed without description of error

**To Reproduce**
1. Go to ur own Campaign u made and own.
2. set fund to contribution
3. Click send (paper plane button)
4. See failed error 

**Expected behavior**
It must be clear message why operation failed - in this case You cannot contribute in your own campaign

**Screenshots**
![image](https://user-images.githubusercontent.com/36797566/148223326-6fe52666-43c1-4023-a6c9-b734013a6d2a.png)

**Comment by DarkNebula0** [comment]
Hey @cryply. Thanks for all the reports and screenshots 👍 

You can always see the error that comes back from the chain in the console.

![Inked148223326-6fe52666-43c1-4023-a6c9-b734013a6d2a](https://user-images.githubusercontent.com/91988910/148224816-a4fb23dd-4ced-4543-a46c-7e4672d49c47.jpg)

**Comment by 2075** [comment]
fair enough, there should be a proper error notification @mikeplanzer ideas?

**Comment by DarkNebula0** [comment]
> fair enough, there should be a proper error notification @mikeplanzer ideas?

 I rather thought about removing the contrebution field when you are the owner
