### ISSUE TITLE
Campaign is not updating up on successful Contribution

### ISSUE THREAD

**Issue by cryply** [gamedaoco/gamedao-beta#267]
**Describe the bug**
U need page refresh to see results of your contribution

**To Reproduce**
1. Go to DAO you belong to.
2. Scroll down to Campaign
4. Contribute something
5. See no updates

**Expected behavior**
amount of backers, contribution funds should/can be affected.

**Comment by soundyogi** [comment]
oh good catch!

**Comment by soundyogi** [comment]
oops I think this is being addressed already ^^; should be reviewable soon.
