### ISSUE TITLE
Cannot create organization as address is not recognised as valid

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-beta#272]
**Describe the bug**
When trying to create an organization I get an error message regarding my address format even though it is a correct Zero address.

**To Reproduce**
1. Go to Organizations and click  +New DAO
2. See Controller and Treasury Account contains no Zero address
3. add 2 different zero addresses
4. See error saying invalid account
5.

**Expected behavior**
Zero account wallets should be valid.

**Screenshots**
![image](https://user-images.githubusercontent.com/91988132/148694979-4fa0df8c-47db-4b48-928e-5b3008230060.png)

**Comment by soundyogi** [comment]
hm I am confused about address formats:

<img width="791" alt="image" src="https://user-images.githubusercontent.com/3201046/148704801-bf99ac18-5fe5-4133-8c8c-d72f256349d1.png">

**Comment by soundyogi** [comment]
on on my old wallet I could select "allow use only on ZERO.io" which also gives 3YpU 
so our code is correct.

however my wallet is wrong... (and I choose display in ZERO format)

**Comment by soundyogi** [comment]
https://github.com/gamedaoco/gamedao-beta/pull/274
