### ISSUE TITLE
International email addresses is not supported at DAO creation

### ISSUE THREAD

**Issue by cryply** [gamedaoco/gamedao-beta#273]
**Describe the bug**
Any Unicode email is not valid

**To Reproduce**
1. Go to beta.gamedao.co
2. Click on "New DAO"
3. Enter any Unicode email
4. See that email is not valid.

**Expected behavior**
According to https://en.wikipedia.org/wiki/International_email
any of 
用户@例子.广告               (Chinese, Unicode)
अजय@डाटा.भारत               (Hindi, Unicode)
квіточка@пошта.укр          (Ukrainian, Unicode)
χρήστης@παράδειγμα.ελ       (Greek, Unicode)
Dörte@Sörensen.example.com  (German, Unicode)
коля@пример.рф              (Russian, Unicode)

are valid emails.

**Screenshots**
![image](https://user-images.githubusercontent.com/36797566/148701419-f8bc90d0-505a-4b5b-b5b4-86e56d101f73.png)

**Comment by 2075** [comment]
all kind of exotic top level domains as well

**Comment by 5-mark** [comment]
deprecated: no email addresses more at DAO createion
