### ISSUE TITLE
Admin button doing nothing

### ISSUE THREAD

**Issue by cryply** [gamedaoco/gamedao-beta#278]
**Describe the bug**
ADMIN button is not working

**To Reproduce**
1. Go to geamedao beta site
2. Click on ADMIN button
3. See nothing changed

**Expected behavior**
It ether should be DISABLED or it should work. Or if intention was to show that user is admin of DAO make it with some other TAG control or STATUS control. Using button is against UX.

**Screenshots**
![image](https://user-images.githubusercontent.com/36797566/149654484-11848469-230b-4f32-a402-52b176f2da0c.png)

**Comment by 2075** [comment]
true, it lacks a view, containing e.g. settings (onchain) and edit (ipfs data) capabilities.
@mikeplanzer @5-mark @soundyogi

**Comment by soundyogi** [comment]
Issue: #302 

disabled Admin button for beta
