### ISSUE TITLE
Homepage view

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-beta#290]
## User Story
As a beta User I want a welcoming, visual appealing Homepage with an explanation of the site / tokens and hints for the questing system 

## Acceptance Criteria

1. Display message on top of the site with a warning like background:
WARNING: All assets in the current TESTNET are for testing purposes only and have no real value.
Please follow our [Documentation](https://docs.gamedao.co/) to get testnet tokens quick.
2. Display further a message which states that in the discord channel buglog the feedback can be given.
3. Add hints to the quest system (wallet and faucet/tokens)

**Comment by 2075** [comment]
is this for gamedao.co or beta.gamedao.co? @5-mark

**Comment by soundyogi** [comment]
Discussion Ticket:
https://github.com/gamedaoco/gamedao-beta/issues/300

**Comment by soundyogi** [comment]
PR that started the current Figma:
https://github.com/gamedaoco/gamedao-beta/pull/193

**Comment by soundyogi** [comment]
oh I assumed its about the beta.

**Comment by soundyogi** [comment]
OK hijacking this after talking to Inan:

![image](https://user-images.githubusercontent.com/3201046/153322039-6148f24a-f2a0-46f2-b138-eb7fb1fbe28f.png)

I cleaned a bit up. We need to shorten the texts. I think something like gentle hints at the first 2 Quests.
something in the line of:
1: hint wallet a link to the docs
2: hint faucet "can you find this icon?" - **icon of faucet**

**Comment by soundyogi** [comment]
https://github.com/gamedaoco/gamedao-beta/pull/313
