### ISSUE TITLE
remove 3d char from non related campaigns

### ISSUE THREAD

**Issue by 2075** [gamedaoco/gamedao-beta#293]
**Describe the bug**
as a campaign creator i want to be able to create a campaign without 3d content of another campaign.

**To Reproduce**
 create campaign
look at detail page
see 3d character from other campaign

**Expected behavior**
no 3d character if you did not upload it

**Screenshots**
<img width="684" alt="image" src="https://user-images.githubusercontent.com/1140449/150940817-a0e72102-8da8-4a9d-aa24-b7334ab5d648.png">

**Comment by 5-mark** [comment]
closed with PR #297
