### ISSUE TITLE
Discussion: GameDAO Landing Page Design

### ISSUE THREAD

**Issue by soundyogi** [gamedaoco/gamedao-beta#300]
We need to discuss the landing page design:
Current Beta:
![image](https://user-images.githubusercontent.com/3201046/151235187-1750739b-3c78-4bc2-a917-9c6298c1180f.png)

Current Figma Design:
![image](https://user-images.githubusercontent.com/3201046/151235410-b582fbe2-f38b-4cd8-9aa1-5cc9850d317b.png)

There is a PR that started to implement the figma, but input is needed to move forward - or maybe we need to challenge the "low poly monitor" concept

**Comment by 5-mark** [comment]
closed as discussion happens not in this ticket
