### ISSUE TITLE
offer 20 minutes runtime for campaign

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-beta#301]
## User Story
As beta user I want to test fast so I can get fast results when creating a campaign.

## Acceptance Criteria

1. Offer 20 minutes as runtime for a campaign on beta.gamedao.co on top of the options in the selectbox
2. Offer 20 minutes as runtime for a proposal on beta.gamedao.co on top of the options in the selectbox

## Additional Information

- we dont want users to wait a day to fund a campaign or close a voting.

## How to test
- [ ] Go to new campaign form and see in the campaign duration selectbox the value 20 min on top of the list
- [ ] See Campaign end in 20min
- [ ] Go to create proposal form and see in the  Duration selectbox the value 20 min on top of the list
- [ ] See proposal end in 20min

**Comment by soundyogi** [comment]
Campaign:
![image](https://user-images.githubusercontent.com/3201046/151239398-af275fdd-32e0-4438-9531-bc29aa2d2eaf.png)

Proposal:
![image](https://user-images.githubusercontent.com/3201046/151239461-6545fb72-c254-4362-af33-214d19aec7f9.png)

PR:
#303
