### ISSUE TITLE
Long title does not fit into window

### ISSUE THREAD

**Issue by seamidori** [gamedaoco/gamedao-beta#307]
**Describe the bug**
When the title of an organisation is to long it went out of window size.

![title](https://user-images.githubusercontent.com/98415280/151672647-0887635c-6dc7-4142-ae90-fc80a2516c98.jpg)

**Comment by 5-mark** [comment]
@soundyogi first of all we should use the list view shown here:
https://www.figma.com/file/LmFOAGwKieWxmLtFVulChX/?node-id=450%3A8720
which means we should have the correct tiles before we (eg.) adapt the maximum input characters for the title. 
The List page should have 3 Organizations (same as campaigns) in a row on a tile view.

**Comment by 5-mark** [comment]
closed as design will change and maxlength and behaviour is defined in create dao form and organisation card
