### ISSUE TITLE
Closed Beta Testing Access

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-beta#309]
## Context
As early beta testing user I want to have access to GameDAO protocols so I can test the platform. 

## Tasks
[ ] create discord bot which sends NFTs to a wallet address
[ ] create NFTs on RMRK and send them to discord bot sender address
[ ] access restriction on beta.gamedao.co #310 
[ ] quests page #311
[ ] success messages #312
[ ] quest page icon #331 

## Additional Information
beta test user process should work like this:
1. beta test user gets into a private discord channel
2. beta test user asks discord bot with a message to receive an access key by providing his address (only 1 key per address)
3. beta test user receives access key into his wallet (best case with a link to see the key)
4. beta test user goes to beta.gamedao.co and sees a landing page where he can enter the beta and is redirected to the /app page
4.1 /app page consists of a teaser, "Access key needed" container, how to get started container, connect wallet container
4.2 on wallet connect the platform checks if the key is in one of the wallets and allows the user to interact with the page (logs in the user, wallet is connected)
4.3 if there is no  access key in the users wallet addresses the user receives a snack bar message about there is no key in the wallet and how to obtain the key link (/app page) (wallet is not connected) (same page 
5. A new navigation point (Quests) is visible in the left navigation for loggedin users
6. Quests page contains  welcome message, quests in boxes, quest status visible and links provided to the feedback form

**Comment by mikeplanzer** [comment]
Info: added additional task to replace icon in navigation
