### ISSUE TITLE
Quests Page

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-beta#311]
## User Story
As beta test user I want to see which quests I have to solve and if I solved them successfully so I know when I am done. 

## Acceptance Criteria

1. a new quests page is created (/quests)
2. a new navigation point is added "Quests" between Campaigns and Faucet
3. Quests page contains of 
3.1 Image teaser box which changes the visual on each quest (6 visuals)
3.2 illustrated "monitor" box consisting of 
3.2.1 a quests navigation which highlights on each quest the active quest number and previous quests with a checkmark which is always clickable when highlighted (linking on the corresponding quest) (see screenshot 1 or figma)
3.2.2 If not highlighted the quest is not clickable
3.3 a text area 
3.3.1 the text is displayed in a type writing style (like eg. Fallout).
3.3.2 pressing "SPACE" or mouseclick skips the typewriting and displays the text immediately 
3.3.3. a CTA which is not active when the quest is not solved and becomes active when the quest is solved

4. Quests intro screen: 
4.1 no navigation point is active and clickable 
4.2 text is displayed, call to action ("PLAY NOW") is active  and links to quest 1

5. Quest 1: Receive Tokens from the faucet 
5.1 solved if ZERO tokens in connected wallet
5.2 not solved status: text and link to docs (https://docs.gamedao.co/guides/installing-your-wallet#3.-get-some-zero-game-and-play-tokens)
5.3 solved status: display image, text and active CTA  

6. Quest 2: Create DAO 
6.1 solved if DAO was created by connected wallet
6.2 not solved status: text and link to docs (https://docs.gamedao.co/guides/from-dao-to-campaign#creating-an-organisation)  
6.3 solved status: Display image, text and active CTA  

7. Quest 3: Get 3 members into your DAO  
7.1 solved if member count of any DAO created by connected wallet are >= 3
7.2 not solved status: text and link to discord beta channel (https://discord.gg/kNTTE8eZX6)
7.3 solved status: Display image, text and active CTA   

 
8. Quest 4: create fundraising campaign 
8.1 solved if connected wallet created a campaign
8.1 not solved status: text and link to docs (https://docs.gamedao.co/guides/from-dao-to-campaign#creating-a-campaign)
8.2 Quest container solved status: Display image, text and active CTA  

8. Quest 5: Get campaign funded 
8.1. solved if any campaign created by connected wallet is funded
8.2 not solved status: text and link to discord beta channel (https://discord.gg/kNTTE8eZX6)
8.3 solved status: Display image, text and active CTA   

9. Quest 6: Create proposal 
9.1. solved if connected wallet created a withdrawal proposal for a campaign
9.1 not solved status: text and link to docs (https://docs.gamedao.co/fundamentals/fundraising/fundraising-withdrawal-proposal) 
9.3 solved status: Display image, text and active CTA   

10. Quest Endgame (get withdrawal proposal passed)
10.1 solved if withdrawal proposal was passed with majority of YES votings
10.2 not solved status: text and link to discord beta channel (https://discord.gg/kNTTE8eZX6)
10.3 solved status: display text and CTA linking to typeform questionnaire: (https://dsgl4ddr6q4.typeform.com/to/NRkTEtFl)

12. The text on top of the screen is shown in 3 colors for the different types of speakers
12.1 Hawkins: Yellow: #FFEF63
12.2 You: Pink: #FF5BBE
12.3 Story Teller: #56FFD4

## Additional Information

All in one documentation: https://docs.google.com/document/d/16hwbSsDKSdCG7mtmxAd_5fbb3LUQkN0a2dmAc3hJ9d0/edit#heading=h.djink8b70oig 

Design Spec: https://www.figma.com/file/7i2hvG20BsRPpuDf8J88Oe/Closed-Beta?node-id=515%3A427349

## Screenshots
1. ![image](https://user-images.githubusercontent.com/91988132/155322437-607a7b2e-3413-4b29-8011-6591bb3f5cae.png)

## How to test

1. hold access NFT in your wallet with a user who did not create anything on chain
2. go through all quests and make sure to look at the page and see the right content on each step 
3. fill out the typeform and ensure addresses are stored somewhere and can be retrieved

**Comment by 2075** [comment]
I really pledge for having simple flowcharts inside the issues to clarify, what do you think

**Comment by mikeplanzer** [comment]
[header_img.zip](https://github.com/gamedaoco/gamedao-beta/files/8125626/header_img.zip)

Please find header visuals in the ZIP attached

**Comment by mikeplanzer** [comment]
[ExportLayers_QuestPage.zip](https://github.com/gamedaoco/gamedao-beta/files/8127278/ExportLayers_QuestPage.zip)

As discussed, please find attached the export of the various layers from the quest page.
@soundyogi @DarkNebula0

**Comment by 5-mark** [comment]
@DarkNebula0: looks awesome so far 🤩  👏🏼  🙌🏼 
First test results:

## General findings: 
- On each reload of the quest page the text is written again with the typewriter. Maybe a click to skip (display full text) would help. Or when the quest is solved (if you know before, the text could be shown without typewriting)
-  autoscroll to bottom when button is visible could make sense as after a long text is shown which needs more space than the monitor has, the button is not visible (see Quest4)
- @mikeplanzer: I think the task headline in general could be bigger to understand WHAT to do. What do you think? 

## Quest findings:
Q2:
- the tasks mentions "DAOs" in plural, should be singular (just "DAO")
- documentation link is not linked

Q3:
- discord link is not linked
- @mikeplanzer I think the text regaring discord could be better. What do you think? "If you need more member you can ask around in the discord community" ...or so

Q4 
- documentation link is not linked
- after campaign creation I do not get a "quest solved" success message
- going to quest page after campaign creation I first have to wait until the text is there and then click on next does not result in anything. Seems like the system does not recognize that I did  solve the quest. 
- from here I am stuck 🛑

**Comment by mikeplanzer** [comment]
## Additional findings:

- The font-weight (font within monitor) should be changed / added to: "font-weight: 600"
- The font-size (font within monitor) should be increased to 1.1rem
- The line height (font within monitor) should be reduced to 1.3 
- The scan-lines are overflowing the monitor. They should be sitting inside the green border of the monitor
![image](https://user-images.githubusercontent.com/25332596/156633433-fa682113-28c6-4eea-999d-b58fbd4b6598.png)

- If the content does not fit into the monitor, there should be an indication via scrollbar that there is more to show
See design here: 

- The spacing between the step indicator circles should be reduced (see design)
- In general the button and step indicator circles seem a bit to small. Should be increased to original size.

**Comment by soundyogi** [comment]
added docs and discord links @5-mark 

changed monitor text @mikeplanzer 

will try to figure out the progress bugs now

**Comment by soundyogi** [comment]
Q4 fixed, added styled scrollbars

**Comment by 5-mark** [comment]
- open links in new tab. 
- Q3 link contains ")" at the end, pls remove

**Comment by 5-mark** [comment]
Landingpage: 
- turn off left navigation (there must be setting for that)
- Headline line height smaller, use color as in figma
- add discord link to beta invite: https://discord.gg/YZT2QANG5m
- add documentation link to: https://docs.gamedao.co/guides/installing-your-wallet
- use paragraphs and text as in figma, please add a ":" at the end of the last sentence

Quest 1: discord link is not underlined
Quest 1: some Hawkins text is still green. (sorry cannot get to first quest anymore.)
Quest 2: "You pop your tape into the DATASETTE PLAYER on your desktop and press play."  --> should be green.
General: try to add autoscroll to scroll to bottom

@soundyogi
@DarkNebula0 
@2075

**Comment by soundyogi** [comment]
Landingpage:

- [ ] turn off left navigation (there must be setting for that)
- [ ] add discord link to beta invite: https://discord.gg/YZT2QANG5m
- [ ] add documentation link to: https://docs.gamedao.co/guides/installing-your-wallet

Quest:
- [ ] Quest 1: some Hawkins text is still green. (sorry cannot get to first quest anymore.)
- [ ] Quest 2: "You pop your tape into the DATASETTE PLAYER on your desktop and press play." --> should be green.
- [ ] General: try to add autoscroll to scroll to bottom

**Comment by soundyogi** [comment]
@5-mark which discord link is not underlined? this is quest 1:
![image](https://user-images.githubusercontent.com/3201046/156848601-aa2ab3a2-bf16-4a3b-a0f3-473333e07ced.png)
