### ISSUE TITLE
frontend corrections for closed beta launch

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-beta#324]
## User Story
As closed beta test user I want to be as least confused as possible browsing and using GameDAO so I can get through all the quests

## Acceptance Criteria

1. Add ZERO currency to all input fields where currency have to be entered  (see screenshot A (just without the " (ZERO)" next to "Membership Fee", and use "TextField with Icon" from MUI)
1.1 the membership fee field in the Create DAO form
1.2 the deposit GAME field  (also remove " (GAME)")
1.3 the Funding target field (also remove " (PLAY)")
2. remove static step indicator on create campaign page (see screenshot B)

## Screenshots

A) 
<img width="412" alt="image" src="https://user-images.githubusercontent.com/91988132/154359531-d1dc8f3b-72db-48f5-8afb-146750098a89.png">

B) 
<img width="440" alt="image" src="https://user-images.githubusercontent.com/91988132/154359254-b159224f-3e1c-409b-870f-adeda7a0c362.png">

## How to test

1. a
2. b
3. c
4. d

**Comment by soundyogi** [comment]
#2 works exactly as intended I dont see the need to fix

PR: #325
