### ISSUE TITLE
[Governance] Create Proposal

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-beta#33]
## Context
As organization member I want to take part in the governance of the organization so I can contribute steering main strategies and decisions of the organization.

## Tasks

[ ] create a proposal for a DAO
[ ] create a proposal for a successful campaign
[ ] select voting mechanism
[ ] submit proposal

**Comment by 2075** [comment]
why closed?

**Comment by 5-mark** [comment]
we have the current create proposal in the current status already. Will organize differently this Epic.
