### ISSUE TITLE
Show castle icon in navigation for quest page

### ISSUE THREAD

**Issue by mikeplanzer** [gamedaoco/gamedao-beta#331]
## User Story
As a ux designer I want to add a castle icon to the navigation for the quest page to have more game style.

## Acceptance Criteria

1. The navigation on the left shows the castle icon

## Additional Information
Castle icon svg attached to this ticket

## How to test

1. Open GameDAO Beta
2. See if castle icon is shown

**Comment by mikeplanzer** [comment]
[icon-castle.zip](https://github.com/gamedaoco/gamedao-beta/files/8173615/icon-castle.zip)

**Comment by mikeplanzer** [comment]
@DarkNebula0 / @soundyogi can one of you please take up this ticket. ty!

**Comment by soundyogi** [comment]
aye

**Comment by soundyogi** [comment]
![image](https://user-images.githubusercontent.com/3201046/156472719-ad9b1818-80ee-4c53-93e3-2f13d9f25f90.png)
![image](https://user-images.githubusercontent.com/3201046/156472759-7ca25f1e-1b0c-4ac9-822d-510059561d6a.png)

the icon size doesnt seem to fit with the others

**Comment by soundyogi** [comment]
https://github.com/gamedaoco/gamedao-beta/pull/332

**Comment by 2075** [comment]
![image](https://user-images.githubusercontent.com/1140449/156522652-473906c7-9667-4d10-b4d2-33b587f1d959.png)

**Comment by soundyogi** [comment]
@mikeplanzer please check the iconsize for me.  thank you <3

**Comment by mikeplanzer** [comment]
@soundyogi, can you try this one: 
![icon-castle](https://user-images.githubusercontent.com/25332596/156664013-4595c6d6-6767-4f0b-8535-f2352e5d6b5c.svg)

Not to sure what went wrong

**Comment by soundyogi** [comment]
![image](https://user-images.githubusercontent.com/3201046/156668420-7dabe7a7-dac7-4ba5-a1c4-cf394dd48e43.png)

yumyumyumyum
