### ISSUE TITLE
Overhaul Validator Tutorial

### ISSUE THREAD

**Issue by soundyogi** [gamedaoco/gamedao-beta#333]
Description:

"subkey" needs the mnemonic seed phrase now to spit out both key formats.

Hence we cannot use the faucet bot anymore since its public.

Instead of compiling subkey yourself lets try using a docker container - also can simplify the whole process via script (folder creation etc.)

**Comment by 2075** [comment]
why is the faucet bot deprecated?
subkey is always the recent one in the subzero docker: ``` docker run -it playzero/subzero:latest /usr/local/bin/subkey
```
