### ISSUE TITLE
[API] set up API Sidecar with subzero node

### ISSUE THREAD

**Issue by 2075** [gamedaoco/gamedao-beta#35]
https://github.com/paritytech/substrate-api-sidecar

**Comment by vovacha** [comment]
@2075 
I'm in the middle of testing right now. Sending native balance works well. I'm going to attach some reports at the end.

I wonder how to deal with not native balances. I assume we should use a module that implements the `MultiCurrency` trait and after some investigation, I've found `orml.rs`, but the code is commented. So what's the way how we work with not native assets? Maybe it's implemented somehow through smart contracts?

**Comment by 2075** [comment]
@vovacha Good questions, I can see you are getting your hands deeper into substrate now :).

ORML is not compatible with our current codebase. Therefore we are using balances and assets pallets to implement all assets. With ORML we can get some additional freedoms.

Current Plan is to work in November on porting all existing pallets to a new Substrate version, where all the internal pallet dependencies (not our own ones) are referenced externally. This will make the repo much lighter and more compatible to the current state of substrate, including ORML.

We can also go via ink contracts, it is already available on the testnet, feel free to use it already!

Where to go next:

1. Let's discuss a fresh node branch with current state and remove internal dependencies (paths) to external ones (urls) so we can keep building and still have the full feature set of the substrate full node (the template node simply doesnt cut it if you want to build a net).
2. Port to cumulus to start testing parachain
3. Add ORML

What are your thoughts?
Also, we can move this discussion to the zero repo maybe, as it is more specific to the subzero node development.

**Comment by 2075** [comment]
- https://github.com/gamedaoco/gamedao-parachain
- https://github.com/gamedaoco/subzero

**Comment by vovacha** [comment]
> Also, we can move this discussion to the zero repo maybe, as it is more specific to the subzero node development.

@2075  I can create corresponding issues for the `gamedao/subzero` repo and `gamedao/gamedao-parachain` as well, but I think firstly we should enable the "Issues" feature there with the assumption that we've moved from `playzero/subzero`.

Based on our discussion I see the next issues:

1. **Provide API interfaces for subzero modules** (ex. sense module).
And API testing with native and non-native assets as a pre-requisites/discovery phase.   No questions so far, working on it. 
2. **Move to a new template with a full feature set of the Substrate full node.**
 What we are trying to achieve is clear. How we are going to do it (remove dependencies, etc.) - we can discuss it in a separate issue.   
3. **Port to cumulus to start testing parachain.**
Could you please elaborate on this a bit more? What exactly are we going to port? I assume that everything related to the PLAY and GAME token goes from `subzero` repo to the `gamedao-parachain` (like crowdfunding and governance modules), but still not sure how to separate it properly.
4. **Add ORML  .**
I assume this one is from `gamedao-parachain` scope, so far no questions.

Maybe we can use GitHub's Discussions feature for some of these, never used it before.

cc: @iZeroIO

**Comment by 2075** [comment]
hey @vovacha

no worries, the parachain repo is more for context, this requires some additional work later, not for now.

1. correct, will be super helpful.
2. later stage
3. later stage. generally the structure of a node is a little different in terms of freedoms. could to understand the parachain tutorial to have it as info in the back of your head
4. also later stage. just to get a general grasp of architecture.

as 1-4 are more about learning, the following are more about what we need to work on in no particular order:

a. writing tests for our pallets ( we can discuss )
b. benchmarking for our pallets ( there is a special procedure )
c. hardening the existing code and extend with missing features.
d. migrating to new pallet syntax

example use case:

- user creates identity which integrates with kilt and **sense** pallet
- user creates a dao in the frontend:
-- on chain this creates an entity with certain parameters (**control** pallet)
- whitelisted accounts can immediately create and vote on proposals (**governance** pallet)  
- when creating a dao, this should automatically mint nfts through **tangram** pallet:
-- e.g. when a new member joins a dao 
-- e.g. when a contributor dedicates funds to a campaign, which completes
-- e.g. when a product is ready to use as a NFT license for the game (not existing as dedicated pallet yet)

in terms of active contribution, i assume time being spent on writing tests (makes us robust and auditable and discovers issues) and benchmarking helps the most and gives you a better understanding of the codebase.

all of this might require to migrate our node and runtime to a more current version or, thus the info above, set up a minimal node where we can migrate the pallets one by one to the new syntax.

**Comment by vovacha** [comment]
1. API sidecar testing was finished (using `Assets` pallet as it was suggested before and `txwrapper-core` for making API calls and signing transactions).

2. I'd like to clarify the task of providing API interfaces whether I got it right.

> ... so we do not expose the fullnodes to api calls, but the sidecar.

So, we don't expose RPC API at all (or partially limit access with RPC proxy) and open only HTTP API.

> ... sense modules/sense/readme.md for a demonstrator, exposing storage and extrinsics through api sidecar

**Extrinsics** (modRep, modTrust, etc.) - I think this should be done with POST transaction endpoint anyway, so I don't see any changes here. Or did you mean something else?

**Storage** - `substrate-api-sidecar` changes: I need to create a service and a controller for the `Sense` pallet and use RPC "state_getStorage" under the hood (or some existing abstraction with the same idea).

And since it's only for the learning purpose there is no need to commit any changes.

@2075 does it make Sense to you? 🙃

**Comment by 2075** [comment]
hey @vovacha,
excellent, this is the expected conclusion.

we need to find ways to achieve:
a. have less load on full nodes
b. provide easy access to api consumers, e.g. a unity3d game

next goal for this would be to have an example integration of rpc endpoints and complete an example pallet to make it ready for production.

## pallet

resulting tasks on pallet level:
- update sense pallet to feature provide rpc endpoints
- write tests for sense pallet
- write benchmarking for sense pallet
- document your work
- commit a pull request with your work in progress code in the subzero dev branch

## graphql

the next part in the stack would be to look at:
- https://github.com/playzero/substrate-graph and
- https://github.com/subquery/subql

our approach back then was to create a primitive stack to index all on chain data, store it in a postgresql and expose it through a graphql api. hasura provides a good grade of automation to achive this on the consumer side. downside in our stack was the missing decoding, as we used substrate-archive and their development also stalled in terms of decoding.

subquery built something similar, but i never found the time to look into it properly.

the ultimate goal is to unload the nodes and have a graphql interface for queries — and eventually find a smart way to sign transactions to be able to mutate chain state.

tasks:
- investigate substrate-graph, substrate-archive, subquery
- set up subquery for a subzero node
- create a docker setup
- document in a PR at subzero repo

in case of questions, reach out. we can also have pair programming session or live coding together.
