### ISSUE TITLE
Website Layout: Left Navigation

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-beta#39]
## User Story
As GameDAO user I want to access main categories of the produict so I can browse the app effectively.

## Acceptance Criteria

1. Main categories 
- Dashboard (Link to "my Dashboard Page": login restricted )
- Organizations (Link to "Organzations List Page")
- Campaigns (Link to "Campaigns List Page")
- Vote (Link to "my Organizations Page": login restricted)
- Tangram (Link to "Tangram Page")
- Documentation  (Link to gitbook)
2. Social Media links
- Discord https://discord.gg/EBg9HQmn8p
- Twitter https://twitter.com/gamedaoco
- Telegram https://t.me/gamedaoco
- Medium https://blog.gamedao.co/
3. Day/Night Mode switcher
4. Language selector (only english for now, makes sense to prepare templates for translation tool?)

## Additional Information

Epic-Link: Website Layout #26 
Figma: https://www.figma.com/file/LmFOAGwKieWxmLtFVulChX/GameDAO-Frontend-Design?node-id=115%3A8111

## How to test

1. all internal links lead to an existing page
2. all external links lead to GameDAO content
2. login restricted pages prompt a wallet connect
3. Day/Night mode 
4. only enghlish as a language for now

**Comment by soundyogi** [comment]
![image](https://user-images.githubusercontent.com/3201046/139962090-b10ed175-4180-47c7-8511-5bb03542ae53.png)

**Comment by michelalbers** [comment]
Checkout #45

**Comment by 2075** [comment]
@mikeplanzer any ETA on the icons? or tell me which lib :dango:

**Comment by mikeplanzer** [comment]
> @mikeplanzer any ETA on the icons? or tell me which lib 🍡

hey @2075, batch one is now uploaded as you've probably already seen:
https://github.com/gamedaoco/gamedao-beta/tree/main/public/assets

**Comment by 2075** [comment]
is this completed? i guess the related PR (already merged) is this: https://github.com/gamedaoco/gamedao-beta/pull/45
but e.g. the item counts are missing, anything else?

@mikeplanzer @iZeroIO @michelalbers

**Comment by soundyogi** [comment]
https://github.com/gamedaoco/gamedao-beta/issues/66

**Comment by 5-mark** [comment]
@michelalbers can you update the social media links, twitter is missing, the links are wrong and discord shows up twice. linkedin was meant for the footer.

**Comment by 2075** [comment]
@5-mark @michelalbers already done in my wip branch
