### ISSUE TITLE
[Documentation] Create GitBook

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-beta#44]
## Context
As user I want to have a documentation of the product so I can inform myself about all relevant topics.

## Tasks
eg like: https://docs.astar.network/
- write techincal documentation for modules so we can start onboarding with Acala
- write how it works....
- tokenomics etc.

**Comment by 2075** [comment]
the gitbook is already created.
shall we have subtasks for documentation?

**Comment by 2075** [comment]
https://github.com/gamedaoco/documentation

**Comment by iZeroIO** [comment]
https://docs.gamedao.co/
