### ISSUE TITLE
Frontend: Refactor List and TileViews for Organisation and Campaigns.

### ISSUE THREAD

**Issue by soundyogi** [gamedaoco/gamedao-beta#50]
Refactor List and TileViews for Organisation and Campaigns. 
Dummy Components in /designsystem

**Comment by soundyogi** [comment]
![image](https://user-images.githubusercontent.com/3201046/140416646-af538625-fd18-4df0-aae0-12baf7d717b1.png)

**Comment by soundyogi** [comment]
Tableview, Listview, Tileview for Organisations /  Campaigns

![image](https://user-images.githubusercontent.com/3201046/140416976-2e430c9c-e087-4d04-a381-f11195faf46e.png)

**Comment by 2075** [comment]
if possible expand the view when user clicks more items per page vs scrollbox

**Comment by 2075** [comment]
Apply to 
- Organisations
- Campaigns
- Tangram
- Governance

@iZeroIO maybe different tickets required

**Comment by soundyogi** [comment]
https://github.com/gamedaoco/gamedao-beta/pull/57
@DarkNebula0

**Comment by soundyogi** [comment]
I guess this deprecates the need for a condensed table view.

Tile and List should be enough (List could get condensed version if needed)

**Comment by 5-mark** [comment]
@soundyogi there is also #9. is that ticket deprecated and we can close it as campaigns page is mentioned here?

**Comment by soundyogi** [comment]
ok closed
