### ISSUE TITLE
Add Iconfont for Icons instead of SVG

### ISSUE THREAD

**Issue by soundyogi** [gamedaoco/gamedao-beta#60]
https://github.com/gamedaoco/gamedao-beta/pull/59

**Comment by mikeplanzer** [comment]
@soundyogi , Font can be found here: gamedao-beta/public/assets/font/

let me know if you need anything else

**Comment by soundyogi** [comment]
https://github.com/gamedaoco/gamedao-beta/issues/63

**Comment by 5-mark** [comment]
@mikeplanzer please test and click the close button, if ok.
