### ISSUE TITLE
lines x shadow/glow

### ISSUE THREAD

**Issue by 2075** [gamedaoco/gamedao-beta#64]
@mikeplanzer are the lines intended like this? how to handle glowyglow then?

<img width="479" alt="image" src="https://user-images.githubusercontent.com/1140449/141018600-33753389-8c5e-4082-a60f-79331b4aa507.png">

<img width="405" alt="image" src="https://user-images.githubusercontent.com/1140449/141018627-2620a178-484c-46ee-a0c3-772b0e49af29.png">

**Comment by 5-mark** [comment]
glowy glow will be removed with task "[alman] implement wallet from figma (wallet UI)"
