### ISSUE TITLE
Sidebar design issues: Size, spacing and font

### ISSUE THREAD

**Issue by mikeplanzer** [gamedaoco/gamedao-beta#66]
**Issues**:
1. Width of sidebar should be according to design = 275px
2. Increase margin of single nav entries
3. Increase font size

![image](https://user-images.githubusercontent.com/25332596/141203555-dbfd4883-5f8c-4eeb-bba2-3c5b401a51bb.png)

**Comment by mikeplanzer** [comment]
@soundyogi , @michelalbers , @DarkNebula0 could one of you please take up this ticket.

**Comment by soundyogi** [comment]
![image](https://user-images.githubusercontent.com/3201046/141240895-0915e3d3-9645-41c9-9ac3-e9a1e5f3039a.png)

**Comment by mikeplanzer** [comment]
Successfully tested. Bug closed.
