### ISSUE TITLE
Update global font to Noto Sans Display

### ISSUE THREAD

**Issue by mikeplanzer** [gamedaoco/gamedao-beta#68]
## User Story
As I UX Manager I want to integrate a new global font which is used for all areas of gamedao to add more uniqueness.

## Acceptance Criteria

1. Implement Noto Sans as the global font on gamedao.co
2. Replace existing font styles with new one
3. Following stylings should be considered
  3.1 Extra-light 200
  3.2 Extra-light 200 italic
  3.3 Regular 400
  3.4 Regular 400 italic
  3.5 Semi-bold 600
  3.6 Extra-bold 800

## Additional Information
Link: https://fonts.google.com/noto/specimen/Noto+Sans+Display

## How to test

1. Open GameDAO.co
2. Check if new font was implemented 
3.

**Comment by soundyogi** [comment]
https://github.com/gamedaoco/gamedao-beta/pull/99
