### ISSUE TITLE
Frontend: Update form styling

### ISSUE THREAD

**Issue by mikeplanzer** [gamedaoco/gamedao-beta#69]
## User Story
As a ux manager I want to update the form stylings to be inline with the brand styling

## Acceptance Criteria

1. Update font styling according to design: https://www.figma.com/file/LmFOAGwKieWxmLtFVulChX/GameDAO-Frontend-Design?node-id=449%3A4887 

![image](https://user-images.githubusercontent.com/25332596/141355544-2a82ffb3-18d8-407e-8c83-8bdc68b4f928.png)

## How to test

1. Check if form styles are updated according to design

**Comment by 2075** [comment]
how does this influence markdown editor? can a user upload n images here, and use them in markdowneditor? @soundyogi

**Comment by soundyogi** [comment]
no, images are uploaded via a button in the markdown editor.
so the whole editor is missing here basically

**Comment by soundyogi** [comment]
it doesnt matter though we can implement this already. (should be able to get quite far just with the theme file)


@michelalbers ping

**Comment by mikeplanzer** [comment]
Done, also with changes from #168
