### ISSUE TITLE
Sidebar - active page not highlighted

### ISSUE THREAD

**Issue by mikeplanzer** [gamedaoco/gamedao-beta#73]
**Describe the bug**
The active (selected) page should be highlighted

**To Reproduce**
1. Go to gamedao.co/app
2. Select a page

**Expected behavior**
Active page is highlighted as per design

**Screenshots**
![image](https://user-images.githubusercontent.com/25332596/141368610-ca3abbf8-caf2-4be0-9ae0-909e37f425cf.png)

**Comment by 5-mark** [comment]
@mikeplanzer & @soundyogi should the background be highlighted too?

**Comment by soundyogi** [comment]
@michelalbers I think this already worked no? somehow we broke it again, sorry - can you have a look

**Comment by michelalbers** [comment]
Well it works partially - its only the font color thats changing rn. Do we want the background, too?

**Comment by 2075** [comment]
@mikeplanzer @michelalbers ideally like in the design, what do you think?

**Comment by mikeplanzer** [comment]
Yes, background of active (selected) page should aswell be highlighted with the background.
@michelalbers / @2075
